### PR TITLE
App4 updates for Use Case Category and Codes

### PR DESCRIPTION
**Pull request by DylanHainsworthNHSD**
Updated Use Case Category for BaRS with both App4 and updated App6 codes after our discussion to make sure they reference the use cases they are intended for.

Updated all the Validation examples to include the use case Category in the SR.

### CODE REVIEW

**Review by Goslinl — APPROVED** [review]

**Review by NaminderSoorma — CHANGES_REQUESTED** [review]
The code has a missing char 'd':
999casvaliation
Should read 999casvalidation

**Comment by DylanHainsworthNHSD** [comment]
@NaminderSoorma This has now been updated in multiple files as i copied that value.

**Review by NaminderSoorma — CHANGES_REQUESTED** [review]
[MessageDefinition/BARS-MessageDefinition-ServiceRequest-Request-Validation.xml]

code is still in-correct

**Comment by DylanHainsworthNHSD** [comment]
@NaminderSoorma Well spotted. Hope that's the end of them.

**Review by NaminderSoorma — APPROVED** [review]

**Pull request merged**
