### PR TITLE
use case context updates

### PR DESCRIPTION
**Pull request by julieharris37**
Use case context updates to all apps

How does this work
Payloads

Carl to check Apps 1,2 and 5
Dylan to check Apps 3,4 and 6
LG to check pseudocode update on App6

### CODE REVIEW

**Review by Goslinl — COMMENTED** [review]
the core use case category pages should be versioned now ie:

topic: core-SPUseCaseCategories-1.0.3

**Comment by julieharris37** [comment]
> the core use case category pages should be versioned now ie:
> 
> topic: core-SPUseCaseCategories-1.0.3

Thanks -  I will update those links in all the apps

**Review by DylanHainsworthNHSD — COMMENTED** [review]
Payloads for requestors App4 - the version number for Core doesn't look correct. "1.1.3"?

Then in App6 How does it work there is an App5 code "a5t1" it should be "a6t1"

**Comment by julieharris37** [comment]
> Payloads for requestors App4 - the version number for Core doesn't look correct. "1.1.3"?
> 
> Then in App6 How does it work there is an App5 code "a5t1" it should be "a6t1"

Updated and recommitted

**Review by Goslinl — APPROVED** [review]

**Comment by cda69** [comment]
@julieharris37  - Against APP5 could we include somewhere that the use-case category 'referraltopharmacy' is now deprecated?

**Comment by julieharris37** [comment]
> @julieharris37 - Against APP5 could we include somewhere that the use-case category 'referraltopharmacy' is now deprecated?

Have added *Please note that the use-case category 'referraltopharmacy' is now deprecated to allow for more granular use cases.*

**Review by cda69 — APPROVED** [review]

**Pull request merged**
