### PR TITLE
Changes made to deployment pages including addition of diagrams

### PR DESCRIPTION
**Pull request by natalieburrell**

### CODE REVIEW

**Review by cda69 — CHANGES_REQUESTED** [review]
The section on the activity of DoS Leads needs to be retained somewhere so we can direct them on how to enable a service for BaRS. 
Also, the table with the environment endpoints is a useful reference, along with links to BaRS onboarding.
Finally, this cannot be merged straight to main.

**Review by DylanHainsworthNHSD — CHANGES_REQUESTED** [review]
You cannot remove an Index page. This is how the navigation to this area works. To me removing the pages removes the linked navigation to the left. A user will now need to scroll through the page to find any relevant sections. If the Phases or steps described has changed then the page name could be updated with them.

**Review by cda69 — APPROVED** [review]
The Roles and Responsibilities section needs work longer term and should align with the RASCI matrix in the beta guide.

**Comment by DylanHainsworthNHSD** [comment]
There is a new PR to replace this one.

**Pull request closed without merging**
