### PR TITLE
Update Examples, MD, CS

### PR DESCRIPTION
**Pull request by DylanHainsworthNHSD**
Updated examples to include UseContext where it was missing. Also updated bundle version to match the Application version, updated MessageDef version to match application version dropping the patch, updated Capability Statement with Core Version.

### CODE REVIEW

**Review by Goslinl — CHANGES_REQUESTED** [review]
Do we not want the Display element in all use case category codings? i thought that was a directive we follow?

**Comment by DylanHainsworthNHSD** [comment]
@Goslinl what we agreed was that the display should not be used for display in your app but can remain in the message for support purposes only.

**Review by Goslinl — COMMENTED** [review]
Yes, I beleive the need for it was for support and not for the end user but as a rule we show display elements in payloads.

**Comment by DylanHainsworthNHSD** [comment]
@Goslinl those are now updated.

**Review by Goslinl — APPROVED** [review]

**Review by cda69 — APPROVED** [review]

**Pull request merged**
